apiVersion: v1
kind: Secret
metadata:
  name: notary-tls
type: Opaque
data:
  root-ca.crt: |
{{ .Files.Get "fixtures/root-ca.crt" | b64enc | indent 4 }}
  notary-server.crt: |
{{ .Files.Get "fixtures/notary-server.crt" | b64enc | indent 4 }}
  notary-server.key: |
{{ .Files.Get "fixtures/notary-server.key" | b64enc | indent 4 }}
  notary-signer.crt: |
{{ .Files.Get "fixtures/notary-signer.crt" | b64enc | indent 4 }}
  notary-signer.key: |
{{ .Files.Get "fixtures/notary-signer.key" | b64enc | indent 4 }}
  database-ca.pem: |
{{ .Files.Get "fixtures/database/ca.pem" | b64enc | indent 4 }}
  notary-server.pem: |
{{ .Files.Get "fixtures/database/notary-server.pem" | b64enc | indent 4 }}
  notary-server-key.pem: |
{{ .Files.Get "fixtures/database/notary-server-key.pem" | b64enc | indent 4 }}
  notary-signer.pem: |
{{ .Files.Get "fixtures/database/notary-server.pem" | b64enc | indent 4 }}
  notary-signer-key.pem: |
{{ .Files.Get "fixtures/database/notary-server-key.pem" | b64enc | indent 4 }}

---

apiVersion: v1
kind: Secret
metadata:
  name: notarysigner-alias-secret
type: Opaque
data:
  alias-secret: {{ required "The secret for the signer alias is required!" .Values.signer.aliasSecret | b64enc }}