apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: server
    spec:
      containers:
      - args:
        - -c
        - ./migrations/migrate.sh && notary-server -config=fixtures/server-config.json
        command:
        - /usr/bin/env
        - sh
        image: ntahri/notaryserver
        name: server
        ports:
        - containerPort: 8080
        - containerPort: 4443
        resources: {}
      restartPolicy: Always
status: {}

