apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: signer
  name: signer
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: signer
    spec:
      containers:
      - args:
        - -c
        - ./migrations/migrate.sh && notary-signer -config=fixtures/signer-config.json
        command:
        - /usr/bin/env
        - sh
        image: ntahri/notarysigner
        name: signer
        ports:
        - containerPort: 7899
        resources: {}
      restartPolicy: Always
status: {}
